### ISSUE TITLE
Newtonsoft.Json dependency

### ISSUE THREAD

**Issue by alexsandro-xpt** [pasientskyhosting/docker-mono-apache#1]
I'm try run a Web Services witch depends of Newtonsoft.Json instaled by Nuget at Windows under Visual Studio and it's work fine..

But, when I try build my project under Mono under this image, I receive a follow message:

`error CS0246: The type or namespace name `JsonConvert' could not be found. Are you missing an assembly reference?`

Why mono can't recognize Newtonsoft.Json dependency?

**Comment by woopstar** [comment]
Sorry. But this image is actually used for internal usage at PatientSky.

We do not use the Newtonsoft.Json package and does not provide support for it yet.

**Comment by alexsandro-xpt** [comment]
Alright, I'm use that image, I replace Newtonsoft.Json to `new JavaScriptSerializer().Serialize(obj)`.

Thank you.
